version: '3.1'

services:

  wordpress:
    container_name: wordpress  
    image: wordpress:latest
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html  
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress

  db:
    container_name: mysql 
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password  
    restart: "always"
    volumes:
      - ./db:/var/lib/mysql        
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  phpmyadmin: 
    container_name: phpmyadmin     
    depends_on:      
    - db    
    image: phpmyadmin/phpmyadmin    
    links:      
    - db    
    ports:      
    - "8080:80"    
    restart: "always"
    
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: "always"
    ports:
      - 1025:1025
      - 8025:8025 
